### ISSUE TITLE
how to change support jquery?

### ISSUE THREAD

**Issue by neozhu** [hyperatom/json-form-data#4]
$.jsonToFormData

**Comment by hyperatom** [comment]
Hi neoznhu, what is the benefit of accessing the function from the jQuery object?

**Comment by neozhu** [comment]
Just habit，

**Comment by hyperatom** [comment]
I would recommend using the function from the window object. I don't have any plans to add it to the jQuery object unless more people request this. Cheers, Adam.

**Comment by Finesse** [comment]
There is absolutely no need to integrate it to jQuery. Also, [you might not need jQuery](http://youmightnotneedjquery.com) at all because all the actual browsers use the same API to work with DOM and AJAX.
